### ISSUE TITLE
In _extractPlaceInfo function the basic.address isn't fine for international location extraction

### ISSUE THREAD

**Issue by roothema** [mlisook/paper-input-place#30]
Hi,

The current _extractPlaceInfo returns with the following: 

> "basic":{  
>       "name":"",
>       "address":"1429-1469 Harrison Street",
>       "city":"San Francisco",
>       "state":"California",
>       "stateCode":"CA",
>       "postalCode":"94103",
>       "country":"Egyesült Államok",
>       "countryCode":"US",
>       "phone":""
>    }

I'm working with international addresses thus it would be nice to include a streetNumber property and remove the street number from the address property so I can use the addresses in a more convinient way.

**Comment by mlisook** [comment]
Thank you for submitting this issue.  I can certainly see how having the street number separate from the address property would be more convenient.  

I also see that for Japan, where the street and number system is not even used, the control does not even fill in the address, for example: search for "Tokyo Solamachi" (the Tokyo Skytree tower).

In the case of the majority of countries using the street and number system, I can add the `streetNumber` property and a new `route` property which would be the `address` with `streetNumber` removed. I can't change the current `address` property because that would break existing uses of the element.

Would that be acceptable?

**Comment by roothema** [comment]
Yes, it's sounds good! Thank you very much.

**Comment by mlisook** [comment]
Version 1.9.6 now includes the change we discussed.
